[package]
name = "rust-webserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

actix-web = "3"
actix = { version = "0.13.0" }
actix-web-actors = { version = "4.2.0" }

tokio = {version = "1.0"}